apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.project }}deamon
      port: {{ .Values.servicedeamon.port }}
      targetPort: http
      protocol: TCP
    - name: {{ .Values.project }}interface
      port: {{ .Values.serviceInterface.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}
